import random
import pandas as pd

# ── Synthetic occupation title generator ─────────────────────────────────────
# Generates realistic messy CRM occupation titles for testing OccuMap
# Designed to cover all classification categories including edge cases
# that trigger human review (NEEDS_REVIEW) for human-in-the-loop demo

random.seed(42)

# ── PME titles (~90) ──────────────────────────────────────────────────────────
pme_clean = [
    "SOFTWARE ENGINEER", "CIVIL ENGINEER", "MECHANICAL ENGINEER",
    "ELECTRICAL ENGINEER", "CHEMICAL ENGINEER", "SYSTEMS ENGINEER",
    "DATA SCIENTIST", "FINANCIAL ANALYST", "BUSINESS ANALYST",
    "MARKETING MANAGER", "OPERATIONS MANAGER", "PRODUCT MANAGER",
    "HUMAN RESOURCE MANAGER", "FINANCE MANAGER", "SALES MANAGER",
    "GENERAL MANAGER", "MANAGING DIRECTOR", "CHIEF EXECUTIVE OFFICER",
    "CHIEF FINANCIAL OFFICER", "CHIEF TECHNOLOGY OFFICER",
    "DOCTOR", "DENTIST", "PHARMACIST", "LAWYER", "ARCHITECT",
    "ACCOUNTANT", "AUDITOR", "ECONOMIST", "PSYCHOLOGIST",
    "REGISTERED NURSE", "SOCIAL WORKER", "TEACHER", "LECTURER",
    "RESEARCH SCIENTIST", "CHEMIST", "BIOLOGIST", "STATISTICIAN",
    "INVESTMENT ANALYST", "COMPLIANCE OFFICER", "RISK MANAGER",
    "PROJECT MANAGER", "PROGRAM MANAGER", "DIRECTOR OF OPERATIONS",
    "SENIOR SOFTWARE ENGINEER", "LEAD DATA SCIENTIST",
    "VICE PRESIDENT OF SALES", "HEAD OF MARKETING",
    "REGIONAL MANAGER", "AREA MANAGER", "BRANCH MANAGER",
    "IT MANAGER", "SECURITY MANAGER", "LOGISTICS MANAGER",
    "SUPPLY CHAIN MANAGER", "PROCUREMENT MANAGER",
    "ENVIRONMENTAL ENGINEER", "BIOMEDICAL ENGINEER",
    "VETERINARIAN", "OPTOMETRIST", "PHYSIOTHERAPIST",
    "OCCUPATIONAL THERAPIST", "SPEECH THERAPIST",
    "MEDICAL SOCIAL WORKER", "CLINICAL PSYCHOLOGIST",
    "PROFESSOR", "PRINCIPAL", "EDUCATION OFFICER",
    "PILOT", "AIR TRAFFIC CONTROLLER", "MARINE SUPERINTENDENT",
    "QUANTITY SURVEYOR", "URBAN PLANNER", "INTERIOR DESIGNER",
    "GRAPHIC DESIGNER", "UX DESIGNER", "CREATIVE DIRECTOR",
    "FUND MANAGER", "PORTFOLIO MANAGER", "INSURANCE UNDERWRITER",
    "SENIOR MANAGER", "ASSISTANT DIRECTOR", "DEPUTY DIRECTOR",
    "PASTOR", "MISSIONARY", "TCM PHYSICIAN",
    "CYBERSECURITY ENGINEER", "DEVOPS ENGINEER", "SOLUTION ARCHITECT",
    "MANAGEMENT CONSULTANT", "STRATEGY CONSULTANT",
]

# ── T titles (~60) ────────────────────────────────────────────────────────────
t_clean = [
    "ENGINEERING TECHNICIAN", "CHEMICAL TECHNICIAN", "LABORATORY TECHNICIAN",
    "MEDICAL TECHNOLOGIST", "PHARMACY TECHNICIAN", "DENTAL TECHNICIAN",
    "PROCESS TECHNICIAN", "PRODUCTION TECHNICIAN", "AIRCRAFT TECHNICIAN",
    "ELECTRICAL TECHNICIAN", "MECHANICAL TECHNICIAN", "IT TECHNICIAN",
    "NETWORK TECHNICIAN", "TELECOMMUNICATIONS TECHNICIAN",
    "RADIOGRAPHER", "PHYSIOTHERAPY ASSISTANT", "MEDICAL LAB TECHNICIAN",
    "PRESCHOOL TEACHER", "CHILDCARE TEACHER", "INFANT CARE TEACHER",
    "DRIVING INSTRUCTOR", "FLIGHT INSTRUCTOR", "FITNESS INSTRUCTOR",
    "PHOTOGRAPHER", "VIDEOGRAPHER", "SOUND TECHNICIAN",
    "POLICE OFFICER", "IMMIGRATION OFFICER", "CUSTOMS OFFICER",
    "FIRE OFFICER", "CIVIL DEFENCE OFFICER",
    "SHIP OFFICER", "DECK OFFICER", "MARINE OFFICER",
    "IT SUPPORT ANALYST", "HELPDESK ANALYST", "SYSTEMS ANALYST",
    "QUALITY CONTROL TECHNICIAN", "QA TECHNICIAN", "MAINTENANCE TECHNICIAN",
    "FACILITY TECHNICIAN", "BUILDING TECHNICIAN", "HVAC TECHNICIAN",
    "SURVEY TECHNICIAN", "CARTOGRAPHIC TECHNICIAN",
    "ACCOUNTING TECHNICIAN", "LEGAL EXECUTIVE", "PARALEGAL",
    "PROPERTY EXECUTIVE", "REAL ESTATE AGENT", "INSURANCE AGENT",
    "TRAVEL CONSULTANT", "TOURISM OFFICER",
    "SOCIAL SERVICE ASSOCIATE", "COMMUNITY DEVELOPMENT OFFICER",
    "HEALTH PROMOTION OFFICER", "ENVIRONMENTAL HEALTH OFFICER",
    "SPORTS COACH", "RECREATION OFFICER",
]

# ── RNF titles (~75) ──────────────────────────────────────────────────────────
rnf_clean = [
    "TAXI DRIVER", "BUS DRIVER", "GRAB DRIVER", "PRIVATE HIRE DRIVER",
    "DELIVERY DRIVER", "TRUCK DRIVER", "FORKLIFT OPERATOR",
    "CRANE OPERATOR", "MACHINE OPERATOR", "PRODUCTION OPERATOR",
    "RETAIL ASSISTANT", "SHOP ASSISTANT", "CASHIER", "PROMOTER",
    "WAITER", "WAITRESS", "BARISTA", "BARTENDER", "COOK", "CHEF",
    "KITCHEN ASSISTANT", "FOOD STALL ASSISTANT", "HAWKER",
    "SECURITY OFFICER", "SECURITY GUARD", "LIFEGUARD",
    "CLEANER", "OFFICE CLEANER", "HOUSEKEEPING ATTENDANT",
    "GENERAL WORKER", "FACTORY WORKER", "PRODUCTION WORKER",
    "WELDER", "ELECTRICIAN", "PLUMBER", "CARPENTER", "PAINTER",
    "AIR CONDITIONING TECHNICIAN", "MOTOR VEHICLE MECHANIC",
    "HAIRDRESSER", "BEAUTICIAN", "MANICURIST", "MASSEUR",
    "POSTMAN", "DESPATCH RIDER", "FOOD DELIVERY RIDER",
    "HEALTHCARE ASSISTANT", "NURSING AIDE", "PATIENT CARE ASSISTANT",
    "CONFINEMENT LADY", "DOMESTIC HELPER",
    "DATA ENTRY CLERK", "RECEPTIONIST", "ADMIN CLERK",
    "SHIPPING CLERK", "LOGISTICS CLERK", "STORE KEEPER",
    "ACCOUNTS CLERK", "BILLING CLERK", "PAYROLL CLERK",
    "CALL CENTRE AGENT", "CUSTOMER SERVICE OFFICER",
    "PRINTING OPERATOR", "PRESS OPERATOR",
    "PEST CONTROL TECHNICIAN", "LANDSCAPE WORKER",
    "BUTCHER", "FISHMONGER", "STALL VENDOR",
    "SCHOOL ATTENDANT", "CANTEEN ASSISTANT",
    "BUS CAPTAIN", "TRAIN OFFICER",
]

# ── Abbreviated versions (~30) ────────────────────────────────────────────────
abbreviated = [
    "SNR SOFTWARE ENGR", "ASST MGR HR", "SR PROJECT MGR",
    "MAINT TECH", "PROD ENGR", "QA ENGR",
    "HR EXEC", "MKTG EXEC", "OPS EXEC",
    "ASST ACCTS MGR", "SNR ACCTS EXEC", "FIN ANALYST",
    "IT SUPP ANALYST", "SYS ADMIN", "NW ENGR",
    "ASST STORE KEEPER", "SR CUST SVC EXEC", "LOGISTIC SUPVR",
    "SNR HR OFFICER", "ASST FINANCE MGR", "SR MKTG MGR",
    "PROD SUPERVISOR", "QC INSPECTOR", "MAINT FITTER",
    "SNR TECHNICIAN", "ASST ENGINEER", "ENGR ASST",
    "SNR EXEC OPS", "ASST ADMIN OFFICER", "SR ACCTS ASST",
]

# ── Typo versions (~15) ───────────────────────────────────────────────────────
with_typos = [
    "CLERCIAL OFFICER", "VEHICAL INSPECTOR", "HAIRSTYLIST",
    "PRODUCATION PACKER", "MECHNICAL ENGINEER", "ADMINSTRATOR",
    "COORDINTOR", "RECPTIONIST", "TECHNCIAN",
    "ACOUNTS EXECUTIVE", "MARKETTING MANAGER", "ENGINNEERING ASST",
    "SUPREVISOR", "OPERTION MANAGER", "FINANACE ANALYST",
]

# ── Ambiguous — will trigger NEEDS_REVIEW (~20) ───────────────────────────────
ambiguous = [
    "SUPERVISOR", "ANALYST", "CONSULTANT", "COORDINATOR",
    "DESIGNER", "MANAGER", "EXECUTIVE", "OFFICER",
    "INSPECTOR", "PLANNER", "TECHNOLOGIST", "SPECIALIST",
    "ASSOCIATE", "TRAINER", "OPERATOR", "DEALER",
    "ENGINEER", "DIRECTOR", "LEADER", "ADVISOR",
]

# ── Status markers — NA (~5) ──────────────────────────────────────────────────
status_na = [
    "RESIGNED", "RETIRED", "HOMEMAKER", "HOUSEWIFE", "RETRENCHED",
]

# ── Real gibberish from actual CRM data — NA (~5) ────────────────────────────
gibberish_na = [
    "TECH", "-", "CSE", "DMS REP", "NIL",
]

# ── Assemble full synthetic dataset ──────────────────────────────────────────
all_titles = (
    pme_clean +
    t_clean +
    rnf_clean +
    abbreviated +
    with_typos +
    ambiguous +
    status_na +
    gibberish_na
)

# Shuffle
random.shuffle(all_titles)

synthetic_df = pd.DataFrame(all_titles, columns=["CRM_OCCUPATION_TITLE"])

print(f"Total synthetic titles: {len(synthetic_df)}")
print(f"\nBreakdown by category:")
print(f"  PME clean:    {len(pme_clean)}")
print(f"  T clean:      {len(t_clean)}")
print(f"  RNF clean:    {len(rnf_clean)}")
print(f"  Abbreviated:  {len(abbreviated)}")
print(f"  With typos:   {len(with_typos)}")
print(f"  Ambiguous:    {len(ambiguous)}")
print(f"  Status NA:    {len(status_na)}")
print(f"  Gibberish NA: {len(gibberish_na)}")
print(f"\nSample titles:")
print(synthetic_df.sample(20, random_state=42).to_string(index=False))